version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  app-base: &app-base
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/urlshortener
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  app1:
    <<: *app-base
    container_name: url-app-1
    ports:
      - "8080:8080"   # Хост 8080 → контейнер 8080

  app2:
    <<: *app-base
    container_name: url-app-2
    ports:
      - "8082:8080"   # Хост 8082 → контейнер 8080

  app3:
    <<: *app-base
    container_name: url-app-3
    ports:
      - "8084:8080"   # Хост 8084 → контейнер 8080
